[package]
name = "cursorcue-render"
version.workspace = true
edition.workspace = true

[dependencies]
cursorcue-core = { path = "../cursorcue-core" }
windows = { version = "0.62", features = ["Win32_Foundation", "Win32_Graphics_Direct3D", "Win32_Graphics_Direct3D_Fxc", "Win32_Graphics_Direct3D11", "Win32_Graphics_Dxgi", "Win32_Graphics_Dxgi_Common"] }
